name: Blanca-website-fe CICD Pipeline

on:
  push:
    branches: 
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.22.0

      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      - name: Generate .env file for develop
        run: |
          touch .env
          echo "BRANCH=develop" >> $GITHUB_ENV

          printf "NEXT_PUBLIC_API_URL=%s\n" "$NEXT_PUBLIC_API_URL" >> .env
          printf "NEXT_PUBLIC_GA_ID=%s\n" "$NEXT_PUBLIC_GA_ID" >> .env
          printf "NEXT_PUBLIC_HOME_PAGE_URL=%s\n" "$NEXT_PUBLIC_HOME_PAGE_URL" >> .env

          ls -la
          cat .env
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
          NEXT_PUBLIC_HOME_PAGE_URL: ${{ secrets.NEXT_PUBLIC_HOME_PAGE_URL }}

      - name: npm build
        run: CI=false npm run build

      - name: Deploy to Server - DEV
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "./"
          TARGET: /root/blanca-website-fe

      - name: Execute Remote SSH Commands - DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            cd /root/blanca-website-fe
            npm install --legacy-peer-deps
            pm2 stop blanca-website-fe || true
            pm2 delete blanca-website-fe || true
            pm2 start npm --name "blanca-website-fe" -- start
